import React from 'react';
import { ContentPlan, GeneratedPoster } from '../types';
import { Share2, Instagram, Download, Image as ImageIcon } from 'lucide-react';

interface SocialPostProps {
  plan: ContentPlan;
  poster: GeneratedPoster;
}

const SocialPost: React.FC<SocialPostProps> = ({ plan, poster }) => {
  // Sanitize filename for download
  const safeFilename = `busan_curator_${plan.title.replace(/[^a-z0-9가-힣]/gi, '_').substring(0, 20)}.png`;

  return (
    <div className="w-full bg-white rounded-2xl shadow-xl overflow-hidden animate-fade-in-up delay-200">
      <div className="bg-gradient-to-r from-purple-600 to-pink-500 p-4 text-white flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Instagram className="w-5 h-5" />
          <span className="font-bold">Generated Post</span>
        </div>
        <div className="flex items-center gap-3 no-print">
          {poster.imageUrl && (
            <a 
              href={poster.imageUrl} 
              download={safeFilename}
              className="text-white/80 hover:text-white transition-colors flex items-center gap-1"
              title="이미지 저장"
            >
              <Download className="w-5 h-5" />
              <span className="text-xs font-medium hidden sm:inline">저장</span>
            </a>
          )}
          <button className="text-white/80 hover:text-white transition-colors">
            <Share2 className="w-5 h-5" />
          </button>
        </div>
      </div>

      <div className="grid md:grid-cols-2">
        {/* Image Section */}
        <div className="bg-slate-100 relative group aspect-square md:aspect-auto">
          {poster.imageUrl ? (
            <>
              <img
                src={poster.imageUrl}
                alt={plan.title}
                className="w-full h-full object-cover"
              />
              <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center no-print">
                <a
                  href={poster.imageUrl}
                  download={safeFilename}
                  className="bg-white text-slate-900 px-4 py-2 rounded-full font-bold flex items-center gap-2 hover:bg-slate-100 transition-colors shadow-lg transform hover:scale-105"
                >
                  <Download className="w-4 h-4" /> 이미지 저장하기
                </a>
              </div>
              <div className="absolute bottom-2 right-2 bg-black/50 text-white text-[10px] px-2 py-1 rounded backdrop-blur-md">
                Generated by Gemini Nano Banana
              </div>
            </>
          ) : (
            <div className="flex items-center justify-center h-full text-slate-400">
              <ImageIcon className="w-12 h-12" />
            </div>
          )}
        </div>

        {/* Text Section */}
        <div className="p-6 flex flex-col justify-center">
          <div className="mb-6">
            <h3 className="font-bold text-slate-800 mb-1">{plan.title}</h3>
            <p className="text-xs text-slate-400 uppercase tracking-widest mb-4">
              {plan.contentType}
            </p>
            <p className="text-slate-600 whitespace-pre-line text-sm leading-relaxed mb-4">
              {plan.socialPostText}
            </p>
            <div className="flex flex-wrap gap-2">
              {plan.hashtags.map((tag, idx) => (
                <span key={idx} className="text-blue-500 text-sm font-medium hover:underline cursor-pointer">
                  #{tag.replace(/^#/, '')}
                </span>
              ))}
            </div>
          </div>
          
          <div className="mt-auto pt-4 border-t border-slate-100 flex items-center justify-between text-xs text-slate-400">
             <span>부산 소울 큐레이터</span>
             <span>AI Collaborative Content</span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SocialPost;